version: '3.8'

services:
  nest-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-api 
    restart: always
    ports:
      - 3001:3001
    depends_on:
      - postgres
    env_file:
      - .env  


  postgresql:
    image: postgres:13
    restart:  always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres:
    name: shop-prisma-docker-db
    